// src/beadData.js
// MARD 全套色卡数据 (约300种)
// 默认设置：数量 1200，预警 200
// 颜色为近似模拟值，导入后可自行修改

const commonProps = { count: 1200, threshold: 200 };

export const mardColors = [
  // === A 系列 (黄色/橙色系 A1-A26) ===
  { name: 'A1', color: '#FFFACD', ...commonProps }, // 柠檬绸
  { name: 'A2', color: '#FFFFF0', ...commonProps }, // 象牙白
  { name: 'A3', color: '#FFF8DC', ...commonProps },
  { name: 'A4', color: '#F0E68C', ...commonProps },
  { name: 'A5', color: '#FFD700', ...commonProps }, // 金色
  { name: 'A6', color: '#FFA500', ...commonProps }, // 橙色
  { name: 'A7', color: '#FF8C00', ...commonProps },
  { name: 'A8', color: '#FFDEAD', ...commonProps },
  { name: 'A9', color: '#F4A460', ...commonProps },
  { name: 'A10', color: '#D2691E', ...commonProps },
  { name: 'A11', color: '#8B4513', ...commonProps },
  { name: 'A12', color: '#A0522D', ...commonProps },
  { name: 'A13', color: '#CD853F', ...commonProps },
  { name: 'A14', color: '#DEB887', ...commonProps },
  { name: 'A15', color: '#FFE4B5', ...commonProps },
  { name: 'A16', color: '#FFEFD5', ...commonProps },
  { name: 'A17', color: '#FFE4C4', ...commonProps },
  { name: 'A18', color: '#FAEBD7', ...commonProps },
  { name: 'A19', color: '#E9967A', ...commonProps },
  { name: 'A20', color: '#FFA07A', ...commonProps },
  { name: 'A21', color: '#FFFFE0', ...commonProps },
  { name: 'A22', color: '#F5F5DC', ...commonProps },
  { name: 'A23', color: '#FAFAD2', ...commonProps },
  { name: 'A24', color: '#EEE8AA', ...commonProps },
  { name: 'A25', color: '#BDB76B', ...commonProps },
  { name: 'A26', color: '#CCCC00', ...commonProps },

  // === B 系列 (绿色系 B1-B32) ===
  { name: 'B1', color: '#98FB98', ...commonProps },
  { name: 'B2', color: '#90EE90', ...commonProps },
  { name: 'B3', color: '#00FF7F', ...commonProps },
  { name: 'B4', color: '#00FA9A', ...commonProps },
  { name: 'B5', color: '#3CB371', ...commonProps },
  { name: 'B6', color: '#2E8B57', ...commonProps },
  { name: 'B7', color: '#228B22', ...commonProps },
  { name: 'B8', color: '#006400', ...commonProps },
  { name: 'B9', color: '#008000', ...commonProps },
  { name: 'B10', color: '#32CD32', ...commonProps },
  { name: 'B11', color: '#00FF00', ...commonProps },
  { name: 'B12', color: '#7CFC00', ...commonProps },
  { name: 'B13', color: '#7FFF00', ...commonProps },
  { name: 'B14', color: '#ADFF2F', ...commonProps },
  { name: 'B15', color: '#556B2F', ...commonProps },
  { name: 'B16', color: '#6B8E23', ...commonProps },
  { name: 'B17', color: '#808000', ...commonProps },
  { name: 'B18', color: '#BDB76B', ...commonProps },
  { name: 'B19', color: '#F0FFF0', ...commonProps },
  { name: 'B20', color: '#F5FFFA', ...commonProps },
  { name: 'B21', color: '#E0FFFF', ...commonProps },
  { name: 'B22', color: '#AFEEEE', ...commonProps },
  { name: 'B23', color: '#7FFFD4', ...commonProps },
  { name: 'B24', color: '#40E0D0', ...commonProps },
  { name: 'B25', color: '#48D1CC', ...commonProps },
  { name: 'B26', color: '#00CED1', ...commonProps },
  { name: 'B27', color: '#20B2AA', ...commonProps },
  { name: 'B28', color: '#008B8B', ...commonProps },
  { name: 'B29', color: '#008080', ...commonProps },
  { name: 'B30', color: '#66CDAA', ...commonProps },
  { name: 'B31', color: '#8FBC8F', ...commonProps },
  { name: 'B32', color: '#2F4F4F', ...commonProps },

  // === C 系列 (蓝色系 C1-C29) ===
  { name: 'C1', color: '#E0FFFF', ...commonProps },
  { name: 'C2', color: '#00FFFF', ...commonProps },
  { name: 'C3', color: '#00BFFF', ...commonProps },
  { name: 'C4', color: '#1E90FF', ...commonProps },
  { name: 'C5', color: '#4169E1', ...commonProps },
  { name: 'C6', color: '#0000FF', ...commonProps },
  { name: 'C7', color: '#0000CD', ...commonProps },
  { name: 'C8', color: '#00008B', ...commonProps },
  { name: 'C9', color: '#191970', ...commonProps },
  { name: 'C10', color: '#87CEFA', ...commonProps },
  { name: 'C11', color: '#87CEEB', ...commonProps },
  { name: 'C12', color: '#ADD8E6', ...commonProps },
  { name: 'C13', color: '#B0C4DE', ...commonProps },
  { name: 'C14', color: '#6495ED', ...commonProps },
  { name: 'C15', color: '#4682B4', ...commonProps },
  { name: 'C16', color: '#5F9EA0', ...commonProps },
  { name: 'C17', color: '#7B68EE', ...commonProps },
  { name: 'C18', color: '#6A5ACD', ...commonProps },
  { name: 'C19', color: '#483D8B', ...commonProps },
  { name: 'C20', color: '#9370DB', ...commonProps },
  { name: 'C21', color: '#8A2BE2', ...commonProps },
  { name: 'C22', color: '#9400D3', ...commonProps },
  { name: 'C23', color: '#9932CC', ...commonProps },
  { name: 'C24', color: '#BA55D3', ...commonProps },
  { name: 'C25', color: '#DA70D6', ...commonProps },
  { name: 'C26', color: '#EE82EE', ...commonProps },
  { name: 'C27', color: '#D8BFD8', ...commonProps },
  { name: 'C28', color: '#E6E6FA', ...commonProps },
  { name: 'C29', color: '#F8F8FF', ...commonProps },

  // === D 系列 (紫色系 D1-D26) ===
  { name: 'D1', color: '#DDA0DD', ...commonProps },
  { name: 'D2', color: '#FF00FF', ...commonProps },
  { name: 'D3', color: '#BA55D3', ...commonProps },
  { name: 'D4', color: '#9370DB', ...commonProps },
  { name: 'D5', color: '#8A2BE2', ...commonProps },
  { name: 'D6', color: '#9400D3', ...commonProps },
  { name: 'D7', color: '#9932CC', ...commonProps },
  { name: 'D8', color: '#8B008B', ...commonProps },
  { name: 'D9', color: '#800080', ...commonProps },
  { name: 'D10', color: '#4B0082', ...commonProps },
  { name: 'D11', color: '#483D8B', ...commonProps },
  { name: 'D12', color: '#6A5ACD', ...commonProps },
  { name: 'D13', color: '#7B68EE', ...commonProps },
  { name: 'D14', color: '#C71585', ...commonProps },
  { name: 'D15', color: '#DB7093', ...commonProps },
  { name: 'D16', color: '#FF1493', ...commonProps },
  { name: 'D17', color: '#FF69B4', ...commonProps },
  { name: 'D18', color: '#FFB6C1', ...commonProps },
  { name: 'D19', color: '#FFC0CB', ...commonProps },
  { name: 'D20', color: '#FAEBD7', ...commonProps },
  { name: 'D21', color: '#F5F5F5', ...commonProps },
  { name: 'D22', color: '#DCDCDC', ...commonProps },
  { name: 'D23', color: '#D3D3D3', ...commonProps },
  { name: 'D24', color: '#C0C0C0', ...commonProps },
  { name: 'D25', color: '#A9A9A9', ...commonProps },
  { name: 'D26', color: '#808080', ...commonProps },

  // === E 系列 (肤色/粉色系 E1-E25) ===
  { name: 'E1', color: '#FFF5EE', ...commonProps }, // 贝壳
  { name: 'E2', color: '#FFDAB9', ...commonProps }, // 桃色
  { name: 'E3', color: '#FFE4E1', ...commonProps }, // 薄雾玫瑰
  { name: 'E4', color: '#FA8072', ...commonProps }, // 鲑鱼
  { name: 'E5', color: '#F08080', ...commonProps }, // 浅珊瑚
  { name: 'E6', color: '#CD5C5C', ...commonProps }, // 印度红
  { name: 'E7', color: '#FF0000', ...commonProps }, // 纯红
  { name: 'E8', color: '#DC143C', ...commonProps }, // 猩红
  { name: 'E9', color: '#B22222', ...commonProps }, // 耐火砖
  { name: 'E10', color: '#8B0000', ...commonProps }, // 深红
  { name: 'E11', color: '#FFC0CB', ...commonProps },
  { name: 'E12', color: '#FFB6C1', ...commonProps },
  { name: 'E13', color: '#FF69B4', ...commonProps },
  { name: 'E14', color: '#FF1493', ...commonProps },
  { name: 'E15', color: '#C71585', ...commonProps },
  { name: 'E16', color: '#DB7093', ...commonProps },
  { name: 'E17', color: '#FF7F50', ...commonProps },
  { name: 'E18', color: '#FF6347', ...commonProps },
  { name: 'E19', color: '#FF4500', ...commonProps },
  { name: 'E20', color: '#FF8C00', ...commonProps },
  { name: 'E21', color: '#FFA500', ...commonProps },
  { name: 'E22', color: '#FFD700', ...commonProps },
  { name: 'E23', color: '#FFFF00', ...commonProps },
  { name: 'E24', color: '#F0E68C', ...commonProps },
  { name: 'E25', color: '#E6E6FA', ...commonProps },

  // === F 系列 (红色系 F1-F25) ===
  { name: 'F1', color: '#FF0000', ...commonProps },
  { name: 'F2', color: '#DC143C', ...commonProps },
  { name: 'F3', color: '#B22222', ...commonProps },
  { name: 'F4', color: '#8B0000', ...commonProps },
  { name: 'F5', color: '#800000', ...commonProps },
  { name: 'F6', color: '#A52A2A', ...commonProps },
  { name: 'F7', color: '#A0522D', ...commonProps },
  { name: 'F8', color: '#8B4513', ...commonProps },
  { name: 'F9', color: '#D2691E', ...commonProps },
  { name: 'F10', color: '#CD853F', ...commonProps },
  { name: 'F11', color: '#F4A460', ...commonProps },
  { name: 'F12', color: '#DEB887', ...commonProps },
  { name: 'F13', color: '#D2B48C', ...commonProps },
  { name: 'F14', color: '#BC8F8F', ...commonProps },
  { name: 'F15', color: '#F5DEB3', ...commonProps },
  { name: 'F16', color: '#FFE4B5', ...commonProps },
  { name: 'F17', color: '#FFDEAD', ...commonProps },
  { name: 'F18', color: '#FAEBD7', ...commonProps },
  { name: 'F19', color: '#FFE4C4', ...commonProps },
  { name: 'F20', color: '#FFDAB9', ...commonProps },
  { name: 'F21', color: '#FFE4E1', ...commonProps },
  { name: 'F22', color: '#FFF0F5', ...commonProps },
  { name: 'F23', color: '#F0F8FF', ...commonProps },
  { name: 'F24', color: '#F8F8FF', ...commonProps },
  { name: 'F25', color: '#FFFAFA', ...commonProps },

  // === G 系列 (棕色系 G1-G23) ===
  { name: 'G1', color: '#8B4513', ...commonProps },
  { name: 'G2', color: '#A0522D', ...commonProps },
  { name: 'G3', color: '#D2691E', ...commonProps },
  { name: 'G4', color: '#CD853F', ...commonProps },
  { name: 'G5', color: '#F4A460', ...commonProps },
  { name: 'G6', color: '#DEB887', ...commonProps },
  { name: 'G7', color: '#D2B48C', ...commonProps },
  { name: 'G8', color: '#BC8F8F', ...commonProps },
  { name: 'G9', color: '#F5DEB3', ...commonProps },
  { name: 'G10', color: '#FFE4B5', ...commonProps },
  { name: 'G11', color: '#FFDEAD', ...commonProps },
  { name: 'G12', color: '#FAEBD7', ...commonProps },
  { name: 'G13', color: '#FFE4C4', ...commonProps },
  { name: 'G14', color: '#FFDAB9', ...commonProps },
  { name: 'G15', color: '#FFE4E1', ...commonProps },
  { name: 'G16', color: '#FFF0F5', ...commonProps },
  { name: 'G17', color: '#F0F8FF', ...commonProps },
  { name: 'G18', color: '#F8F8FF', ...commonProps },
  { name: 'G19', color: '#FFFAFA', ...commonProps },
  { name: 'G20', color: '#FFFFFF', ...commonProps },
  { name: 'G21', color: '#DCDCDC', ...commonProps },
  { name: 'G22', color: '#D3D3D3', ...commonProps },
  { name: 'G23', color: '#C0C0C0', ...commonProps },

  // === H 系列 (灰色/黑白系 H1-H23) ===
  { name: 'H1', color: '#FFFFFF', ...commonProps }, // 纯白
  { name: 'H2', color: '#F5F5F5', ...commonProps },
  { name: 'H3', color: '#DCDCDC', ...commonProps },
  { name: 'H4', color: '#D3D3D3', ...commonProps },
  { name: 'H5', color: '#C0C0C0', ...commonProps },
  { name: 'H6', color: '#A9A9A9', ...commonProps },
  { name: 'H7', color: '#000000', ...commonProps }, // 纯黑
  { name: 'H8', color: '#2F4F4F', ...commonProps },
  { name: 'H9', color: '#696969', ...commonProps },
  { name: 'H10', color: '#708090', ...commonProps },
  { name: 'H11', color: '#778899', ...commonProps },
  { name: 'H12', color: '#B0C4DE', ...commonProps },
  { name: 'H13', color: '#E6E6FA', ...commonProps },
  { name: 'H14', color: '#FFF0F5', ...commonProps },
  { name: 'H15', color: '#F0F8FF', ...commonProps },
  { name: 'H16', color: '#F8F8FF', ...commonProps },
  { name: 'H17', color: '#F5FFFA', ...commonProps },
  { name: 'H18', color: '#FFFFF0', ...commonProps },
  { name: 'H19', color: '#F0FFF0', ...commonProps },
  { name: 'H20', color: '#FFFFE0', ...commonProps },
  { name: 'H21', color: '#FAFAD2', ...commonProps },
  { name: 'H22', color: '#FFEFD5', ...commonProps },
  { name: 'H23', color: '#FFE4B5', ...commonProps },

  // === M 系列 (暗色系 M1-M15) ===
  { name: 'M1', color: '#2F4F4F', ...commonProps },
  { name: 'M2', color: '#556B2F', ...commonProps },
  { name: 'M3', color: '#808000', ...commonProps },
  { name: 'M4', color: '#6B8E23', ...commonProps },
  { name: 'M5', color: '#A0522D', ...commonProps },
  { name: 'M6', color: '#8B4513', ...commonProps },
  { name: 'M7', color: '#A52A2A', ...commonProps },
  { name: 'M8', color: '#800000', ...commonProps },
  { name: 'M9', color: '#8B0000', ...commonProps },
  { name: 'M10', color: '#4B0082', ...commonProps },
  { name: 'M11', color: '#483D8B', ...commonProps },
  { name: 'M12', color: '#2F4F4F', ...commonProps },
  { name: 'M13', color: '#000000', ...commonProps },
  { name: 'M14', color: '#36454F', ...commonProps }, // 炭灰
  { name: 'M15', color: '#1C1C1C', ...commonProps },

  // === P 系列 (珠光系 P1-P23) ===
  { name: 'P1', color: '#F0F8FF', ...commonProps },
  { name: 'P2', color: '#E6E6FA', ...commonProps },
  { name: 'P3', color: '#FFF0F5', ...commonProps },
  { name: 'P4', color: '#FFE4E1', ...commonProps },
  { name: 'P5', color: '#FFDAB9', ...commonProps },
  { name: 'P6', color: '#EEE8AA', ...commonProps },
  { name: 'P7', color: '#F0E68C', ...commonProps },
  { name: 'P8', color: '#98FB98', ...commonProps },
  { name: 'P9', color: '#AFEEEE', ...commonProps },
  { name: 'P10', color: '#B0C4DE', ...commonProps },
  { name: 'P11', color: '#DDA0DD', ...commonProps },
  { name: 'P12', color: '#FFC0CB', ...commonProps },
  { name: 'P13', color: '#F5DEB3', ...commonProps },
  { name: 'P14', color: '#D2B48C', ...commonProps },
  { name: 'P15', color: '#BC8F8F', ...commonProps },
  { name: 'P16', color: '#A9A9A9', ...commonProps },
  { name: 'P17', color: '#DCDCDC', ...commonProps },
  { name: 'P18', color: '#F5F5F5', ...commonProps },
  { name: 'P19', color: '#FFFFFF', ...commonProps },
  { name: 'P20', color: '#FFFAFA', ...commonProps },
  { name: 'P21', color: '#FFFFF0', ...commonProps },
  { name: 'P22', color: '#FAEBD7', ...commonProps },
  { name: 'P23', color: '#FFE4C4', ...commonProps },

  // === R, T 系列 (半透/透明 R1-R28, T1) ===
  { name: 'R1', color: '#FF6347', ...commonProps }, // 透红
  { name: 'R2', color: '#FFA500', ...commonProps },
  { name: 'R3', color: '#FFFF00', ...commonProps },
  { name: 'R4', color: '#00FF00', ...commonProps },
  { name: 'R5', color: '#00FFFF', ...commonProps },
  { name: 'R6', color: '#0000FF', ...commonProps },
  { name: 'R7', color: '#800080', ...commonProps },
  { name: 'R8', color: '#FFC0CB', ...commonProps },
  { name: 'R9', color: '#FFFFFF', ...commonProps }, // 透白
  { name: 'R10', color: '#000000', ...commonProps }, // 透黑
  { name: 'R11', color: '#808080', ...commonProps },
  { name: 'R12', color: '#A52A2A', ...commonProps },
  { name: 'R13', color: '#D2691E', ...commonProps },
  { name: 'R14', color: '#FFD700', ...commonProps },
  { name: 'R15', color: '#C0C0C0', ...commonProps },
  { name: 'R16', color: '#40E0D0', ...commonProps },
  { name: 'R17', color: '#FF1493', ...commonProps },
  { name: 'R18', color: '#00FA9A', ...commonProps },
  { name: 'R19', color: '#1E90FF', ...commonProps },
  { name: 'R20', color: '#BA55D3', ...commonProps },
  { name: 'R21', color: '#FF4500', ...commonProps },
  { name: 'R22', color: '#32CD32', ...commonProps },
  { name: 'R23', color: '#87CEEB', ...commonProps },
  { name: 'R24', color: '#9370DB', ...commonProps },
  { name: 'R25', color: '#FF69B4', ...commonProps },
  { name: 'R26', color: '#F0E68C', ...commonProps },
  { name: 'R27', color: '#E6E6FA', ...commonProps },
  { name: 'R28', color: '#F5FFFA', ...commonProps },
  { name: 'T1', color: '#F0F8FF', ...commonProps }, // 透明 L14

  // === Y 系列 (夜光系 Y1-Y5) ===
  { name: 'Y1', color: '#FFFFE0', ...commonProps }, // 夜光黄
  { name: 'Y2', color: '#F0FFF0', ...commonProps }, // 夜光绿
  { name: 'Y3', color: '#F0F8FF', ...commonProps }, // 夜光蓝
  { name: 'Y4', color: '#FFF0F5', ...commonProps }, // 夜光粉
  { name: 'Y5', color: '#FFFFFF', ...commonProps }, // 夜光白

  // === ZG 系列 (光变/其他) ===
  { name: 'ZG1', color: '#E6E6FA', ...commonProps },
  { name: 'ZG2', color: '#FFE4E1', ...commonProps },
  { name: 'ZG3', color: '#F0FFF0', ...commonProps },
  { name: 'ZG4', color: '#F0F8FF', ...commonProps },
  { name: 'ZG5', color: '#FFFACD', ...commonProps },
  { name: 'ZG6', color: '#F5F5F5', ...commonProps },
  { name: 'ZG7', color: '#DCDCDC', ...commonProps },
  { name: 'ZG8', color: '#D3D3D3', ...commonProps },

  // === Q 系列 (温变 Q1-Q5) ===
  { name: 'Q1', color: '#FFB6C1', ...commonProps },
  { name: 'Q2', color: '#87CEFA', ...commonProps },
  { name: 'Q3', color: '#90EE90', ...commonProps },
  { name: 'Q4', color: '#FFFFE0', ...commonProps },
  { name: 'Q5', color: '#DDA0DD', ...commonProps },

  // === 特殊 ===
  { name: '圣诞红', color: '#FF0000', ...commonProps },
  { name: '圣诞绿', color: '#008000', ...commonProps },
  { name: '混豆', color: '#808080', ...commonProps },
];