// src/beadData.js
// 根据图片录入的 MARD 全套色卡 (精准色值)
// 默认设置：数量 1200，预警 200

const commonProps = { count: 1200, threshold: 200 };

export const mardColors = [
  // === A 系列 (黄色系) ===
  { name: 'A1', color: '#FAF5CD', ...commonProps },
  { name: 'A2', color: '#FCFED6', ...commonProps },
  { name: 'A3', color: '#FCFF92', ...commonProps },
  { name: 'A4', color: '#F7EC5C', ...commonProps },
  { name: 'A5', color: '#F0D83A', ...commonProps },
  { name: 'A6', color: '#FDA951', ...commonProps },
  { name: 'A7', color: '#FA8C4F', ...commonProps },
  { name: 'A8', color: '#FDD94D', ...commonProps },
  { name: 'A9', color: '#F99C5F', ...commonProps },
  { name: 'A10', color: '#F47E36', ...commonProps },
  { name: 'A11', color: '#FEDB99', ...commonProps },
  { name: 'A12', color: '#FDA276', ...commonProps },
  { name: 'A13', color: '#FEC667', ...commonProps },
  { name: 'A14', color: '#F85842', ...commonProps },
  { name: 'A15', color: '#FBF65E', ...commonProps },
  { name: 'A16', color: '#FEFF97', ...commonProps },
  { name: 'A17', color: '#FDE173', ...commonProps },
  { name: 'A18', color: '#FCBF80', ...commonProps },
  { name: 'A19', color: '#FD7E77', ...commonProps },
  { name: 'A20', color: '#F9D66E', ...commonProps },
  { name: 'A21', color: '#FAE393', ...commonProps },
  { name: 'A22', color: '#EDF878', ...commonProps },
  { name: 'A23', color: '#E1C9BD', ...commonProps },
  { name: 'A24', color: '#F3F6A9', ...commonProps },
  { name: 'A25', color: '#FFD785', ...commonProps },
  { name: 'A26', color: '#FEC832', ...commonProps },

  // === B 系列 (绿色系) ===
  { name: 'B1', color: '#DFF139', ...commonProps },
  { name: 'B2', color: '#64F343', ...commonProps },
  { name: 'B3', color: '#9FF685', ...commonProps },
  { name: 'B4', color: '#5FDF34', ...commonProps },
  { name: 'B5', color: '#39E158', ...commonProps },
  { name: 'B6', color: '#64E0A4', ...commonProps },
  { name: 'B7', color: '#3EAE7C', ...commonProps },
  { name: 'B8', color: '#1D9B54', ...commonProps },
  { name: 'B9', color: '#2A5037', ...commonProps },
  { name: 'B10', color: '#9AD1BA', ...commonProps },
  { name: 'B11', color: '#627032', ...commonProps },
  { name: 'B12', color: '#1A6E3D', ...commonProps },
  { name: 'B13', color: '#C8E87D', ...commonProps },
  { name: 'B14', color: '#ACE84C', ...commonProps },
  { name: 'B15', color: '#305335', ...commonProps },
  { name: 'B16', color: '#C0ED9C', ...commonProps },
  { name: 'B17', color: '#9EB33E', ...commonProps },
  { name: 'B18', color: '#E6ED4F', ...commonProps },
  { name: 'B19', color: '#26878E', ...commonProps },
  { name: 'B20', color: '#CAEDCF', ...commonProps },
  { name: 'B21', color: '#176268', ...commonProps },
  { name: 'B22', color: '#0A4241', ...commonProps },
  { name: 'B23', color: '#343B1A', ...commonProps },
  { name: 'B24', color: '#E8FAA6', ...commonProps },
  { name: 'B25', color: '#4E846D', ...commonProps },
  { name: 'B26', color: '#907C35', ...commonProps },
  { name: 'B27', color: '#D0E0AF', ...commonProps },
  { name: 'B28', color: '#9EE5BB', ...commonProps },
  { name: 'B29', color: '#C6DF5F', ...commonProps },
  { name: 'B30', color: '#E3FBB1', ...commonProps },
  { name: 'B31', color: '#B2E694', ...commonProps },
  { name: 'B32', color: '#92AD60', ...commonProps },

  // === C 系列 (蓝色系) ===
  { name: 'C1', color: '#F0FEE4', ...commonProps },
  { name: 'C2', color: '#ABF8FE', ...commonProps },
  { name: 'C3', color: '#9EE0F8', ...commonProps },
  { name: 'C4', color: '#44CDFB', ...commonProps },
  { name: 'C5', color: '#06ABE3', ...commonProps },
  { name: 'C6', color: '#54A7E9', ...commonProps },
  { name: 'C7', color: '#3977CC', ...commonProps },
  { name: 'C8', color: '#0F52BD', ...commonProps },
  { name: 'C9', color: '#3349C3', ...commonProps },
  { name: 'C10', color: '#3DBBE3', ...commonProps },
  { name: 'C11', color: '#2ADED3', ...commonProps },
  { name: 'C12', color: '#1E334E', ...commonProps },
  { name: 'C13', color: '#CDE7FE', ...commonProps },
  { name: 'C14', color: '#D6FDFC', ...commonProps },
  { name: 'C15', color: '#21C5C4', ...commonProps },
  { name: 'C16', color: '#1858A2', ...commonProps },
  { name: 'C17', color: '#02D1F3', ...commonProps },
  { name: 'C18', color: '#213244', ...commonProps },
  { name: 'C19', color: '#18869D', ...commonProps },
  { name: 'C20', color: '#1A70A9', ...commonProps },
  { name: 'C21', color: '#BEDDFC', ...commonProps },
  { name: 'C22', color: '#6BB1BB', ...commonProps },
  { name: 'C23', color: '#C8E2F9', ...commonProps },
  { name: 'C24', color: '#7EC5F9', ...commonProps },
  { name: 'C25', color: '#A9E8E0', ...commonProps },
  { name: 'C26', color: '#42ADD1', ...commonProps },
  { name: 'C27', color: '#D0DEF9', ...commonProps },
  { name: 'C28', color: '#BDCEE8', ...commonProps },
  { name: 'C29', color: '#364A89', ...commonProps },

  // === D 系列 (紫色系) ===
  { name: 'D1', color: '#ACB7EF', ...commonProps },
  { name: 'D2', color: '#868DD3', ...commonProps },
  { name: 'D3', color: '#3653AF', ...commonProps },
  { name: 'D4', color: '#162C7E', ...commonProps },
  { name: 'D5', color: '#B34EC6', ...commonProps },
  { name: 'D6', color: '#B37BDC', ...commonProps },
  { name: 'D7', color: '#8758A9', ...commonProps },
  { name: 'D8', color: '#E3D2FE', ...commonProps },
  { name: 'D9', color: '#D6BAF5', ...commonProps },
  { name: 'D10', color: '#301A49', ...commonProps },
  { name: 'D11', color: '#BCBAE2', ...commonProps },
  { name: 'D12', color: '#DC99CE', ...commonProps },
  { name: 'D13', color: '#B5038F', ...commonProps },
  { name: 'D14', color: '#882893', ...commonProps },
  { name: 'D15', color: '#2F1E8E', ...commonProps },
  { name: 'D16', color: '#E2E4F0', ...commonProps },
  { name: 'D17', color: '#C7D3F9', ...commonProps },
  { name: 'D18', color: '#9A64B8', ...commonProps },
  { name: 'D19', color: '#D8C2D9', ...commonProps },
  { name: 'D20', color: '#9C34AD', ...commonProps },
  { name: 'D21', color: '#940595', ...commonProps },
  { name: 'D22', color: '#383995', ...commonProps },
  { name: 'D23', color: '#EADBF8', ...commonProps },
  { name: 'D24', color: '#768AE1', ...commonProps },
  { name: 'D25', color: '#4950C2', ...commonProps },
  { name: 'D26', color: '#D6C6EB', ...commonProps },

  // === E 系列 (肤色系) ===
  { name: 'E1', color: '#F6D4CB', ...commonProps },
  { name: 'E2', color: '#FCC1DD', ...commonProps },
  { name: 'E3', color: '#F6BDE8', ...commonProps },
  { name: 'E4', color: '#E9639E', ...commonProps },
  { name: 'E5', color: '#F1559F', ...commonProps },
  { name: 'E6', color: '#EC4072', ...commonProps },
  { name: 'E7', color: '#C63674', ...commonProps },
  { name: 'E8', color: '#FDDBE9', ...commonProps },
  { name: 'E9', color: '#E575C7', ...commonProps },
  { name: 'E10', color: '#D33997', ...commonProps },
  { name: 'E11', color: '#F7DAD4', ...commonProps },
  { name: 'E12', color: '#F893BF', ...commonProps },
  { name: 'E13', color: '#B5026A', ...commonProps },
  { name: 'E14', color: '#FAD4BF', ...commonProps },
  { name: 'E15', color: '#F5C9CA', ...commonProps },
  { name: 'E16', color: '#FBF4EC', ...commonProps },
  { name: 'E17', color: '#F7E3EC', ...commonProps },
  { name: 'E18', color: '#FBC8DB', ...commonProps },
  { name: 'E19', color: '#F6BBD1', ...commonProps },
  { name: 'E20', color: '#D7C6CE', ...commonProps },
  { name: 'E21', color: '#C09DA4', ...commonProps },
  { name: 'E22', color: '#B58B9F', ...commonProps },
  { name: 'E23', color: '#937D8A', ...commonProps },
  { name: 'E24', color: '#DEBEE5', ...commonProps },

  // === F 系列 (红色系) ===
  { name: 'F1', color: '#FF9280', ...commonProps },
  { name: 'F2', color: '#F73D4B', ...commonProps },
  { name: 'F3', color: '#EF4D3E', ...commonProps },
  { name: 'F4', color: '#F92B40', ...commonProps },
  { name: 'F5', color: '#E30328', ...commonProps },
  { name: 'F6', color: '#913635', ...commonProps },
  { name: 'F7', color: '#911932', ...commonProps },
  { name: 'F8', color: '#BB0126', ...commonProps },
  { name: 'F9', color: '#E0677A', ...commonProps },
  { name: 'F10', color: '#874628', ...commonProps },
  { name: 'F11', color: '#592323', ...commonProps },
  { name: 'F12', color: '#F8516D', ...commonProps },
  { name: 'F13', color: '#F45C45', ...commonProps },
  { name: 'F14', color: '#FCADB2', ...commonProps },
  { name: 'F15', color: '#D50527', ...commonProps },
  { name: 'F16', color: '#F8C0A9', ...commonProps },
  { name: 'F17', color: '#E89B7D', ...commonProps },
  { name: 'F18', color: '#D07E4A', ...commonProps },
  { name: 'F19', color: '#BE454A', ...commonProps },
  { name: 'F20', color: '#C69495', ...commonProps },
  { name: 'F21', color: '#F2B8C6', ...commonProps },
  { name: 'F22', color: '#F7C3D0', ...commonProps },
  { name: 'F23', color: '#EC806D', ...commonProps },
  { name: 'F24', color: '#E09DAF', ...commonProps },
  { name: 'F25', color: '#E84854', ...commonProps },

  // === Z 系列 (图片里的Z系列) ===
  { name: 'Z1', color: '#DAABB3', ...commonProps },
  { name: 'Z2', color: '#D6AA87', ...commonProps },
  { name: 'Z3', color: '#C1BD8D', ...commonProps },
  { name: 'Z4', color: '#96B69F', ...commonProps },
  { name: 'Z5', color: '#849DC6', ...commonProps },
  { name: 'Z6', color: '#94BFE2', ...commonProps },
  { name: 'Z7', color: '#E2A9D2', ...commonProps },
  { name: 'Z8', color: '#AB91C0', ...commonProps },

  // === G 系列 (棕色系) ===
  { name: 'G1', color: '#FFE4D3', ...commonProps },
  { name: 'G2', color: '#FCC6AC', ...commonProps },
  { name: 'G3', color: '#F1C4A5', ...commonProps },
  { name: 'G4', color: '#DCB387', ...commonProps },
  { name: 'G5', color: '#E7B34E', ...commonProps },
  { name: 'G6', color: '#E3A014', ...commonProps },
  { name: 'G7', color: '#985C3A', ...commonProps },
  { name: 'G8', color: '#713D2F', ...commonProps },
  { name: 'G9', color: '#E4B685', ...commonProps },
  { name: 'G10', color: '#DA8C42', ...commonProps },
  { name: 'G11', color: '#DAC898', ...commonProps },
  { name: 'G12', color: '#FEC993', ...commonProps },
  { name: 'G13', color: '#B2714B', ...commonProps },
  { name: 'G14', color: '#8B684C', ...commonProps },
  { name: 'G15', color: '#F6F8E3', ...commonProps },
  { name: 'G16', color: '#F2D8C1', ...commonProps },
  { name: 'G17', color: '#79544E', ...commonProps },
  { name: 'G18', color: '#FFE4D6', ...commonProps },
  { name: 'G19', color: '#DD7D41', ...commonProps },
  { name: 'G20', color: '#A5452F', ...commonProps },
  { name: 'G21', color: '#B38561', ...commonProps },

  // === H 系列 (灰色/白色) ===
  { name: 'H1', color: '#FBFBFB', ...commonProps },
  { name: 'H2', color: '#FFFFFF', ...commonProps },
  { name: 'H3', color: '#B4B4B4', ...commonProps },
  { name: 'H4', color: '#878787', ...commonProps },
  { name: 'H5', color: '#464648', ...commonProps },
  { name: 'H6', color: '#2C2C2C', ...commonProps },
  { name: 'H7', color: '#010101', ...commonProps },
  { name: 'H8', color: '#E7D6DC', ...commonProps },
  { name: 'H9', color: '#EFEDEE', ...commonProps },
  { name: 'H10', color: '#ECEAEB', ...commonProps },
  { name: 'H11', color: '#CDCDCD', ...commonProps },
  { name: 'H12', color: '#FDF6EE', ...commonProps },
  { name: 'H13', color: '#F4EFD1', ...commonProps },
  { name: 'H14', color: '#CED7D4', ...commonProps },
  { name: 'H15', color: '#98A6A6', ...commonProps },
  { name: 'H16', color: '#1B1213', ...commonProps },
  { name: 'H17', color: '#F0EEEF', ...commonProps },
  { name: 'H18', color: '#FCFFF8', ...commonProps },
  { name: 'H19', color: '#F2EEE5', ...commonProps },
  { name: 'H20', color: '#96A09F', ...commonProps },
  { name: 'H21', color: '#F8FBE6', ...commonProps },
  { name: 'H22', color: '#CACAD2', ...commonProps },
  { name: 'H23', color: '#9B9C94', ...commonProps },

  // === M 系列 (暗色系) ===
  { name: 'M1', color: '#BBC6B6', ...commonProps },
  { name: 'M2', color: '#909994', ...commonProps },
  { name: 'M3', color: '#697E80', ...commonProps },
  { name: 'M4', color: '#E0D4BC', ...commonProps },
  { name: 'M5', color: '#D0CBAE', ...commonProps },
  { name: 'M6', color: '#B0AA86', ...commonProps },
  { name: 'M7', color: '#B0A796', ...commonProps },
  { name: 'M8', color: '#AE8082', ...commonProps },
  { name: 'M9', color: '#A88764', ...commonProps },
  { name: 'M10', color: '#C6B2BB', ...commonProps },
  { name: 'M11', color: '#9D7693', ...commonProps },
  { name: 'M12', color: '#644B51', ...commonProps },
  { name: 'M13', color: '#C79266', ...commonProps },
  { name: 'M14', color: '#C37463', ...commonProps },
  { name: 'M15', color: '#747D7A', ...commonProps },

  // === T/P/R/Y 系列 (特殊) ===
  { name: 'T1', color: '#FCFDFF', ...commonProps },
  
  { name: 'P1', color: '#F9F9F9', ...commonProps },
  { name: 'P2', color: '#ABABAB', ...commonProps },
  { name: 'P3', color: '#B6DBAF', ...commonProps },
  { name: 'P4', color: '#FEA2A3', ...commonProps },
  { name: 'P5', color: '#EB903F', ...commonProps },
  { name: 'P6', color: '#63CEA2', ...commonProps },
  { name: 'P7', color: '#E79273', ...commonProps },
  { name: 'P8', color: '#ECDB59', ...commonProps },
  { name: 'P9', color: '#DBD9DA', ...commonProps },
  { name: 'P10', color: '#DBC7EA', ...commonProps },
  { name: 'P11', color: '#F1E9D4', ...commonProps },
  { name: 'P12', color: '#E9EDEE', ...commonProps },
  { name: 'P13', color: '#ADCBF1', ...commonProps },
  { name: 'P14', color: '#337BAD', ...commonProps },
  { name: 'P15', color: '#668575', ...commonProps },
  { name: 'P16', color: '#FDC24E', ...commonProps },
  { name: 'P17', color: '#FDA42E', ...commonProps },
  { name: 'P18', color: '#FEBDA7', ...commonProps },
  { name: 'P19', color: '#FFDEE9', ...commonProps },
  { name: 'P20', color: '#FCBFD1', ...commonProps },
  { name: 'P21', color: '#E8BEC2', ...commonProps },
  { name: 'P22', color: '#DFAAA4', ...commonProps },
  { name: 'P23', color: '#A3656A', ...commonProps },

  { name: 'R1', color: '#D40E1F', ...commonProps },
  { name: 'R2', color: '#F13484', ...commonProps },
  { name: 'R3', color: '#FB852B', ...commonProps },
  { name: 'R4', color: '#F8ED33', ...commonProps },
  { name: 'R5', color: '#32C958', ...commonProps },
  { name: 'R6', color: '#1EBA93', ...commonProps },
  { name: 'R7', color: '#1D779C', ...commonProps },
  { name: 'R8', color: '#1960C8', ...commonProps },
  { name: 'R9', color: '#945AB1', ...commonProps },
  { name: 'R10', color: '#F8DA54', ...commonProps },
  { name: 'R11', color: '#FCECF7', ...commonProps },
  { name: 'R12', color: '#D8D4D3', ...commonProps },
  { name: 'R13', color: '#56534E', ...commonProps },
  { name: 'R14', color: '#A3E7DC', ...commonProps },
  { name: 'R15', color: '#78CEE7', ...commonProps },
  { name: 'R16', color: '#3FCDCE', ...commonProps },
  { name: 'R17', color: '#4E8379', ...commonProps },
  { name: 'R18', color: '#7DCA9C', ...commonProps },
  { name: 'R19', color: '#C8E664', ...commonProps },
  { name: 'R20', color: '#E3CCBA', ...commonProps },
  { name: 'R21', color: '#A17140', ...commonProps },
  { name: 'R22', color: '#6B372C', ...commonProps },
  { name: 'R23', color: '#F6BB6F', ...commonProps },
  { name: 'R24', color: '#F3C6C0', ...commonProps },
  { name: 'R25', color: '#C76A62', ...commonProps },
  { name: 'R26', color: '#D093BC', ...commonProps },
  { name: 'R27', color: '#E58EAE', ...commonProps },
  { name: 'R28', color: '#9F85CF', ...commonProps },

  { name: 'Y1', color: '#FF6FB7', ...commonProps },
  { name: 'Y2', color: '#FDB583', ...commonProps },
  { name: 'Y3', color: '#D8FCA4', ...commonProps },
  { name: 'Y4', color: '#91DAFB', ...commonProps },
  { name: 'Y5', color: '#E987EA', ...commonProps },
  { name: 'Y6', color: '#F7D4E8', ...commonProps },
  { name: 'Y7', color: '#F1FA7D', ...commonProps },
  { name: 'Y8', color: '#5EE88C', ...commonProps },
  { name: 'Y9', color: '#F8F5FE', ...commonProps },
];